# name: Release

# on:
#   push:
#     branches: [ "develop" ]


# jobs:
#   deploy:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - run: docker build . -t tochukwu1159/continious-deployment-test
#     - run: echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
#     - run: docker push tochukwu1159/continious-deployment-test
